"""_

Revision ID: 124c3e0ab3db
Revises: 23413b2946bf
Create Date: 2024-01-18 15:03:48.696564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124c3e0ab3db'
down_revision: Union[str, None] = '23413b2946bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               sql_nullable=False)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=True)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               sql_nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               sql_nullable=True)
    # ### end Alembic commands ###
