"""_

Revision ID: 23413b2946bf
Revises: 47f005b693f6
Create Date: 2024-01-18 14:51:01.970608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '23413b2946bf'
down_revision: Union[str, None] = '47f005b693f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.alter_column('users', 'admin',
                    existing_type=sa.BOOLEAN(),
                    sql_nullable=False)
    op.alter_column('users', 'active',
                    existing_type=sa.BOOLEAN(),
                    sql_nullable=False)
    op.alter_column('users', 'reg_date',
                    existing_type=sa.DATE(),
                    sql_nullable=False)
    op.alter_column('users', 'upd_date',
                    existing_type=sa.DATE(),
                    sql_nullable=False)
    op.alter_column('users', 'id',
                    existing_type=sa.INTEGER(),
                    sql_nullable=True,
                    autoincrement=True)
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
                    existing_type=sa.INTEGER(),
                    sqk_nullable=False,
                    autoincrement=True)
    op.alter_column('users', 'upd_date',
                    existing_type=sa.DATE(),
                    sql_nullable=True)
    op.alter_column('users', 'reg_date',
                    existing_type=sa.DATE(),
                    sql_nullable=True)
    op.alter_column('users', 'active',
                    existing_type=sa.BOOLEAN(),
                    sql_nullable=True)
    op.alter_column('users', 'admin',
                    existing_type=sa.BOOLEAN(),
                    sql_nullable=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
