"""_

Revision ID: 23c37974b99f
Revises: 321b66bbf791
Create Date: 2024-01-17 15:43:43.743981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c37974b99f'
down_revision: Union[str, None] = '321b66bbf791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=True,
               autoincrement=True)
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=True)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               sql_nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    # ### end Alembic commands ###
