"""last_name

Revision ID: 287cd0d29875
Revises: 45ab2cc06bec
Create Date: 2024-05-19 22:35:26.453493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287cd0d29875'
down_revision: Union[str, None] = '45ab2cc06bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('companies_id_seq'::regclass)"))
    op.create_unique_constraint(None, 'companies', ['id'])
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'locations', ['id'])
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'locations', type_='unique')
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'companies', type_='unique')
    op.alter_column('companies', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('companies_id_seq'::regclass)"))
    # ### end Alembic commands ###
