"""_

Revision ID: 321b66bbf791
Revises: 948aa1e72955
Create Date: 2024-01-17 04:39:14.304098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321b66bbf791'
down_revision: Union[str, None] = '948aa1e72955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=False))
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=True,
               autoincrement=True)
    op.drop_constraint('users_telephone_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_telephone_key', 'users', ['telephone'])
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=True)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
