"""_

Revision ID: 47f005b693f6
Revises: 23c37974b99f
Create Date: 2024-01-17 16:00:33.244420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f005b693f6'
down_revision: Union[str, None] = '23c37974b99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=False)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'upd_date',
               existing_type=sa.DATE(),
               sql_nullable=True)
    op.alter_column('users', 'reg_date',
               existing_type=sa.DATE(),
               sql_nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               sql_nullable=True)
    # ### end Alembic commands ###
