"""_

Revision ID: 948aa1e72955
Revises: 0d62231db295
Create Date: 2024-01-17 04:07:44.812615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948aa1e72955'
down_revision: Union[str, None] = '0d62231db295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=True,
               autoincrement=True)
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               sql_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
